# Site settings
## Change the values as needed.
title: KAVworks Technologies Pvt. Ltd
email: vijay777pawar@gmail.com
description: "A technology company to meet all end to end software requirements of every customer on this planet "
keywords: "kavworks, technology, software, android, website"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "http://blog.kavworks.com" # the base hostname & protocol for your site
#url : "http://127.0.0.1:4000"
baseurl: "" # the subpath of your site, e.g. /blog/   /kavworksblog
paginate: 3
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: kavworks
  twitter: kavworks
  email: contact.kavworks@gmail.com
  github: brijeshb42/bitwiser-material/
exclude:
  - bower_components
  - README.md
full_name: vanchha

##set this to enable disqus commenting
disqus: blog-kavworks-com-1

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in


gems: [jekyll-paginate]
